name: hello_world_dart
publish_to: none # let's not accidentally publish this to pub.dartlang.org

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
